version: "2"
services:
    web:
        build:
         context: ./app
        container_name: online-shop-client
        ports:
            - "8080:8080"
        links:
            - api

    api:
        build:
         context: .
        container_name: online-shop-server
        image: node:11.11.0-alpine
        ports:
            - "5000:5000"
        depends_on:
            - mongodb

    mongodb:
        container_name: online-shop-DB
        image: mongo
        restart: always
        ports:
            - 27017:27017

